import { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  TrendingDown, Share2, Calendar, ArrowLeft, ExternalLink,
  Loader2, Bot, Copy, Check, RefreshCw,
} from 'lucide-react';
import { useAuditStore } from '../store/auditStore';
import { shareApi, auditApi } from '../services/api';
import RecommendationCard from '../components/audit/RecommendationCard';
import { SpendBreakdownPie, SavingsComparisonBar } from '../components/audit/SavingsCharts';
import LeadCaptureModal from '../components/audit/LeadCaptureModal';
import { formatCurrency } from '../lib/utils';
import { SkeletonCard } from '../components/ui/Skeleton';

// ── Stat card ─────────────────────────────────────────────────────────────────
function StatCard({ label, value, sub, accent, delay = 0 }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay }}
      className="card-glass rounded-2xl p-5"
    >
      <p className="text-xs text-gray-500 font-medium mb-2">{label}</p>
      <p className={`text-3xl font-bold ${accent || 'text-white'}`}>{value}</p>
      {sub && <p className="text-xs text-gray-500 mt-1">{sub}</p>}
    </motion.div>
  );
}

// ── AI Summary panel ──────────────────────────────────────────────────────────
function AISummaryPanel({ summary, source, shareId, onRegenerate }) {
  const [regenerating, setRegenerating] = useState(false);

  const handleRegen = async () => {
    setRegenerating(true);
    try { await onRegenerate(); } finally { setRegenerating(false); }
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ delay: 0.4 }}
      className="card-glass rounded-2xl p-6"
    >
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-purple-600 to-brand-600 flex items-center justify-center">
            <Bot className="w-3.5 h-3.5 text-white" />
          </div>
          <div>
            <p className="text-sm font-semibold text-white">AI Executive Summary</p>
            <p className="text-[11px] text-gray-500">{source === 'ai' ? 'Generated by Claude 3.5 Sonnet' : 'Rule-based summary'}</p>
          </div>
        </div>
        <button
          onClick={handleRegen}
          disabled={regenerating}
          id="regenerate-summary"
          className="p-1.5 rounded-lg hover:bg-white/10 text-gray-500 hover:text-white transition-colors disabled:opacity-40"
          title="Regenerate summary"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${regenerating ? 'animate-spin' : ''}`} />
        </button>
      </div>
      <p className="text-sm text-gray-300 leading-relaxed">{summary}</p>
    </motion.div>
  );
}

// ── Share button ──────────────────────────────────────────────────────────────
function ShareButton({ shareId }) {
  const [copied, setCopied] = useState(false);
  const url = `${window.location.origin}/share/${shareId}`;

  const copy = () => {
    navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button
      id="share-audit-btn"
      onClick={copy}
      className="btn-secondary text-sm py-2.5 gap-2"
    >
      {copied ? <Check className="w-3.5 h-3.5 text-accent-400" /> : <Copy className="w-3.5 h-3.5" />}
      {copied ? 'Copied!' : 'Share Audit'}
    </button>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────
export default function ResultsPage() {
  const { shareId: paramShareId } = useParams();
  const navigate = useNavigate();
  const { result: storeResult, shareId: storeShareId } = useAuditStore();

  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [leadOpen, setLeadOpen] = useState(false);
  const [summary, setSummary] = useState('');
  const [summarySource, setSummarySource] = useState('fallback');

  // Determine shareId: from URL param (shared view) or store (fresh audit)
  const shareId = paramShareId || storeShareId;
  const isSharedView = Boolean(paramShareId);

  useEffect(() => {
    if (isSharedView) {
      // Load from API for shared link
      setLoading(true);
      shareApi.getAudit(paramShareId)
        .then(res => {
          setData(res.data);
          setSummary(res.data.aiSummary || '');
          setSummarySource(res.data.summarySource || 'fallback');
        })
        .catch(() => setError('Audit not found or has expired.'))
        .finally(() => setLoading(false));
    } else if (storeResult) {
      // Use fresh result from store
      setData(storeResult);
      setSummary(storeResult.aiSummary || '');
      setSummarySource(storeResult.summarySource || 'fallback');
    } else {
      navigate('/audit', { replace: true });
    }
  }, [paramShareId, isSharedView, storeResult, navigate]);

  const handleRegenSummary = async () => {
    try {
      const res = await auditApi.regenerateSummary(shareId);
      if (res.success) {
        setSummary(res.data.summary);
        setSummarySource(res.data.source);
      }
    } catch {}
  };

  if (loading) {
    return (
      <main className="min-h-screen pt-24 pb-16 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto space-y-5">
          {[1, 2, 3].map(i => <SkeletonCard key={i} />)}
        </div>
      </main>
    );
  }

  if (error) {
    return (
      <main className="min-h-screen pt-24 pb-16 px-4 sm:px-6 flex items-center justify-center">
        <div className="text-center">
          <p className="text-5xl mb-4">🔍</p>
          <h2 className="text-xl font-semibold text-white mb-2">{error}</h2>
          <Link to="/audit" className="btn-primary mt-4">Start a New Audit</Link>
        </div>
      </main>
    );
  }

  if (!data) return null;

  const noSavings = data.totalMonthlySavings === 0;

  return (
    <>
      <main className="min-h-screen pt-24 pb-20 px-4 sm:px-6">
        <div className="max-w-4xl mx-auto">
          {/* Back / breadcrumb */}
          {!isSharedView && (
            <Link to="/audit" className="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-white mb-6 transition-colors">
              <ArrowLeft className="w-3.5 h-3.5" />
              Edit Audit
            </Link>
          )}

          {/* Top actions */}
          <div className="flex items-center justify-between mb-8 gap-4 flex-wrap">
            <div>
              <h1 className="font-display text-3xl sm:text-4xl font-bold text-white">Your Audit Results</h1>
              <p className="text-sm text-gray-500 mt-1 flex items-center gap-1.5">
                <Calendar className="w-3.5 h-3.5" />
                {new Date(data.auditedAt || Date.now()).toLocaleDateString('en-US', { dateStyle: 'long' })}
              </p>
            </div>
            {shareId && <ShareButton shareId={shareId} />}
          </div>

          {/* ── Summary stats ─────────────────────────────────────────────── */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            <StatCard
              label="Current Monthly Spend"
              value={formatCurrency(data.currentMonthlySpend)}
              sub="across all tools"
              delay={0.05}
            />
            <StatCard
              label="Monthly Savings"
              value={formatCurrency(data.totalMonthlySavings)}
              accent="text-accent-400"
              sub="potential reduction"
              delay={0.1}
            />
            <StatCard
              label="Yearly Savings"
              value={formatCurrency(data.totalYearlySavings)}
              accent="text-accent-400"
              sub="annualized"
              delay={0.15}
            />
            <StatCard
              label="Cost Reduction"
              value={`${data.savingsPercentage}%`}
              accent={data.savingsPercentage > 20 ? 'text-accent-400' : 'text-amber-400'}
              sub={`${data.recommendationCount} recommendations`}
              delay={0.2}
            />
          </div>

          {/* ── Charts ────────────────────────────────────────────────────── */}
          {data.toolsAudited?.length > 0 && (
            <div className="grid sm:grid-cols-2 gap-4 mb-6">
              <SpendBreakdownPie toolsAudited={data.toolsAudited} />
              <SavingsComparisonBar
                currentMonthlySpend={data.currentMonthlySpend}
                optimizedMonthlySpend={data.optimizedMonthlySpend}
              />
            </div>
          )}

          {/* ── AI Summary ────────────────────────────────────────────────── */}
          {summary && (
            <div className="mb-6">
              <AISummaryPanel
                summary={summary}
                source={summarySource}
                shareId={shareId}
                onRegenerate={handleRegenSummary}
              />
            </div>
          )}

          {/* ── Recommendations ───────────────────────────────────────────── */}
          <div className="mb-8">
            <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <TrendingDown className="w-4 h-4 text-accent-400" />
              {noSavings ? 'No Issues Found' : `${data.recommendationCount} Optimization${data.recommendationCount !== 1 ? 's' : ''} Found`}
            </h2>

            {noSavings ? (
              <div className="card-glass rounded-2xl p-10 text-center">
                <div className="text-4xl mb-3">✅</div>
                <p className="text-white font-semibold mb-1">Your AI stack looks well-optimized!</p>
                <p className="text-sm text-gray-400">No significant overspending or redundancies detected based on current plans and team size.</p>
              </div>
            ) : (
              <div className="space-y-3">
                {data.recommendations?.map((rec, i) => (
                  <RecommendationCard key={i} rec={rec} index={i} />
                ))}
              </div>
            )}
          </div>

          {/* ── Credex CTA ────────────────────────────────────────────────── */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5 }}
            className="rounded-2xl p-8 text-center"
            style={{ background: 'radial-gradient(ellipse 80% 80% at 50% 0%, rgba(99,102,241,0.2) 0%, rgba(16,24,40,0) 70%), #111128' }}
          >
            <p className="text-xs font-semibold text-brand-400 uppercase tracking-wider mb-2">Free Consultation</p>
            <h2 className="font-display text-2xl font-bold text-white mb-3">
              Want expert help implementing these changes?
            </h2>
            <p className="text-sm text-gray-400 mb-6 max-w-md mx-auto">
              Our Credex team can help you migrate plans, negotiate vendor contracts, and lock in these savings permanently.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
              <button
                id="get-consultation-btn"
                onClick={() => setLeadOpen(true)}
                className="btn-primary px-8 py-3"
              >
                Get Free Consultation
                <ExternalLink className="w-3.5 h-3.5" />
              </button>
              <Link to="/audit" className="btn-secondary py-3 px-6">
                Run Another Audit
              </Link>
            </div>
          </motion.div>
        </div>
      </main>

      <LeadCaptureModal open={leadOpen} onClose={() => setLeadOpen(false)} />
    </>
  );
}
